Repository PandasWhoCode/update-custom-properties, pull requests merged in 2025-04, with the labels that each got.

#6 fix: add security.md file
  .github/SECURITY.md
Labels: enhancement

#8 ci: create a new action to update custom properties in a repo
  .github/SECURITY.md
  action.yaml
  repo-properties.yaml
Labels: enhancement

#15 chore: add conventional pr title check action, contributing, and code-of-conduct
  .github/workflows/validate-conventional-commits.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, chore

#17 docs: update readme
  README.md
Labels: documentation, docs

#19 fix: change custom_properties.json to repo-properties.yaml in readme
  README.md
Labels: bug, documentation, fix
